name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  workflow_dispatch:    # Allow manual triggers

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4    # Updated from v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
           extended: true    # Uncomment if you need SCSS processing

      - name: Build
        run: hugo --minify

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'    # Hugo's output directory
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
